-- Users are managed by Supabase auth schema

create table if not exists public.credentials (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null,
  environment text not null check (environment in ('sandbox','live')),
  enc_client_id text not null,
  enc_client_secret text not null,
  enc_iv text not null,
  enc_salt text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_credentials_user on public.credentials(user_id);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  meta jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_audit_logs_user on public.audit_logs(user_id);

-- RLS
alter table public.credentials enable row level security;
alter table public.audit_logs enable row level security;

create policy credentials_isolation on public.credentials
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy audit_isolation on public.audit_logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


